spring.application.name=payroll-system
server.port=${PORT:8080}
server.address=0.0.0.0

logging.level.org.springframework=INFO
logging.level.com.techup=DEBUG

spring.datasource.url=${SPRING_DATASOURCE_URL:}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

supabase.url=${SUPABASE_URL:}
supabase.bucket=${SUPABASE_BUCKET:uploads}
supabase.apiKey=${SUPABASE_API_KEY:}
jwt.secret=${JWT_SECRET:}
jwt.expiration=${JWT_EXPIRATION:86400000}

spring.config.import=optional:classpath:application-local.properties