CREATE TABLE employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    position VARCHAR(255) NOT NULL,
    base_salary NUMERIC(10, 2) NOT NULL,
    role VARCHAR(255) NOT NULL,
    CONSTRAINT uk_employees_email UNIQUE (email)
);

CREATE TABLE work_shifts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shift_name VARCHAR(255) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    extra_hour_rate NUMERIC(10, 2) NOT NULL
);

CREATE TABLE payrolls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    month INTEGER NOT NULL,
    year INTEGER NOT NULL,
    total_amount NUMERIC(10, 2) NOT NULL,
    status VARCHAR(255) NOT NULL,
    processed_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_payrolls_employee FOREIGN KEY (employee_id) REFERENCES employees (id),
    CONSTRAINT uk_payrolls_employee_month_year UNIQUE (employee_id, month, year)
);

CREATE TABLE shift_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    shift_id BIGINT NOT NULL,
    work_date DATE NOT NULL,
    note VARCHAR(255),
    CONSTRAINT fk_shift_assignments_employee FOREIGN KEY (employee_id) REFERENCES employees (id),
    CONSTRAINT fk_shift_assignments_shift FOREIGN KEY (shift_id) REFERENCES work_shifts (id),
    CONSTRAINT uk_shift_assignments_employee_work_date UNIQUE (employee_id, work_date)
);

CREATE INDEX idx_payrolls_employee_id ON payrolls (employee_id);
CREATE INDEX idx_payrolls_month_year ON payrolls (month, year);
CREATE INDEX idx_shift_assignments_employee_id ON shift_assignments (employee_id);
CREATE INDEX idx_shift_assignments_work_date ON shift_assignments (work_date);
